controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

phonebook_controllers:
    resource: ../../lib/PhonebookBundle/src/Controller/
    type: annotation
